### PR TITLE
Respect users ColorScheme

### PR DESCRIPTION
**Pull request by lambdalisue**
SSIA

### CODE REVIEW

**Comment by Shatur95** [comment]
Hm... I tried, but it looks like only folders are affected:
Without:
изображение
With:
изображение

**Comment by lambdalisue** [comment]
Is your colorscheme provide `g:terminal_ansi_colors` (Vim) or `g:terminal_color_0` (Neovim) ?

**Comment by Shatur95** [comment]
Yes, I have `g:terminal_color_0`.

**Comment by polyzen** [comment]
Before and after:
Before and after

gruvbox: `g:terminal_ansi_colors ['#fbf1c7', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#7c6f64', '#928374', '#9d0006', '#79740e', '#b57614', '#076678', '#8f3f71', '#427b58', '#3c3836']`

**Comment by Shatur95** [comment]
I think my theme defines similar colors. I looked closely, the differences are noticeable, just not very much.

**Comment by lambdalisue** [comment]
Merged. Thanks for testing @Shatur95 @polyzen

**Pull request merged**
